apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-multussubnet1az1-ipv4
spec:
  config: '{
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "ens6",
          "mode": "l2",
          "ipam": {
            "type": "whereabouts",
            "datastore": "kubernetes",
            "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
            "range": "10.0.4.32-10.0.4.63/24",
            "log_file" : "/tmp/whereabouts.log",
            "log_level" : "debug",
            "gateway": "10.0.4.1"
          }
        },
        { 
          "type": "sbr"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-multussubnet2az1-ipv4
spec:
  config: '{
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "ens7",
          "mode": "l2",
          "ipam": {
            "type": "whereabouts",
            "datastore": "kubernetes",
            "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
            "range": "10.0.6.32-10.0.6.63/24",
            "log_file" : "/tmp/whereabouts.log",
            "log_level" : "debug",
            "gateway": "10.0.6.1"
          }
        },
        {
          "type": "sbr"
        }
      ]    
    }'
