apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-multussubnet1az2-ipv4
spec:
  config: '{
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "eth1",
          "mode": "l2",
          "ipam": {
            "type": "whereabouts",
            "datastore": "kubernetes",
            "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
            "range": "10.0.5.32-10.0.5.63/24",
            "log_file" : "/tmp/whereabouts.log",
            "log_level" : "debug",
            "gateway": "10.0.5.1"
          }
        },
        { 
          "type": "sbr"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-multussubnet2az2-ipv4
spec:
  config: '{
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "ipvlan",
          "master": "eth2",
          "mode": "l2",
          "ipam": {
            "type": "whereabouts",
            "datastore": "kubernetes",
            "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
            "range": "10.0.7.32-10.0.7.63/24",
            "log_file" : "/tmp/whereabouts.log",
            "log_level" : "debug",
            "gateway": "10.0.7.1"
          }
        },
        {
          "type": "sbr"
        }
      ]    
    }'
