apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-for-cleartaint
  namespace: cleartaints
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-for-cleartaint-role
rules: # Authorization rules
  - apiGroups: [""]
    #resources: ["nodes", "services", "pods", "endpoints", "serviceaccounts"]
    #verbs: ["get", "list", "watch", "update", "patch"]
    resources: ["nodes"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-for-cleartaint-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sa-for-cleartaint-role
subjects:
  - kind: ServiceAccount
    name: sa-for-cleartaint
    namespace: cleartaints